### PR TITLE
chore: update libsql dep in axum/turso example

### PR DESCRIPTION
**Pull request by Jaco-Minnaar**
## Description of change
Bump `libsql` dependency in `axum/turso` example.

### CODE REVIEW

**Comment by Jaco-Minnaar** [comment]
This change was requested when I opened a PR in the main repo to update the `libsql` dependency: https://github.com/shuttle-hq/shuttle/pull/1694. This is a draft as I can't really test against the updated crate until it is published. 

Please let me know of any additional changes that are needed.

**Comment by oddgrd** [comment]
Thanks @Jaco-Minnaar! You can test the updated crate by using a cargo patch, see this section of the development docs: https://github.com/shuttle-hq/shuttle/blob/main/DEVELOPING.md#apply-patches

**Comment by Jaco-Minnaar** [comment]
> Thanks @Jaco-Minnaar! You can test the updated crate by using a cargo patch, see this section of the development docs: https://github.com/shuttle-hq/shuttle/blob/main/DEVELOPING.md#apply-patches

Pretty cool the things you learn in Open Source! I'll check it out.

**Comment by jonaro00** [comment]
CI now checks the updated example against the updated crate. Some small thing(s) to fix.

**Pull request merged**
