### PR TITLE
feat(examples): Add crontab service

### PR DESCRIPTION
**Pull request by morlinbrot**
Closes shuttle-hq/shuttle#372

Implementation of a simple crontab service by @urbaniak and I. We decided to put this up as a minimal viable PR, implementing a most basic crontab service, that will run a function indefinitely on the provided schedule.

We had a few ideas on added functionality that could make sense, let us know if we should add any of the below to the example or keep it as minimal as it is:

- It may be nice to have some kind of output in the browser when running the project, even if it's only a message saying that there's nothing to see here. I guess this would involve using something like Axum to expose something to the outside, though, this may be too much setup for little "exemplary gains".
- Krzysztof had the great idea of possible evolving this into a mock "invoicing email service" that would send out an email each month. For this, we could also use s3 (and demonstrate its usage) to keep a record of which customers were billed already.
- Another idea would be to make this into a "call API on a schedule" service, replacing a job function with a URL to call. This could also use s3 to keep an actual crontab which could be filled by a very simple browser frontend. The called API would perform the actual job, which may be another shuttle example (e.g. "run example X in another terminal and input its URL here to trigger it on a schedule")

Let us know your thoughts and how to proceed!

### CODE REVIEW

**Comment by jonaro00** [comment]
I think the "call API on a schedule" is a good basic use case for showcasing this feature 👍

**Comment by morlinbrot** [comment]
@urbaniak and I agree that it would probably be best to move forward with this in its minimal form like it is now. Whatever else we might want to expand into could simply become an independent, bigger example.

**Review by iulianbarbu — DISMISSED** [review]
This LGTM as a simple example for custom service implementation. 

nit: I would add the example under `custom_service/crontab`

> It may be nice to have some kind of output in the browser when running the project, even if it's only a message saying that there's nothing to see here. I guess this would involve using something like Axum to expose something to the outside, though, this may be too much setup for little "exemplary gains".

Fair point. It's also the case that if this would be deployed on shuttle it will get a `shuttleapp` domain which might not be needed. I think we'll have to track such use-cases down the line and add the necessary interface for customizing the shuttle services in a representative way.

> Krzysztof had the great idea of possible evolving this into a mock "invoicing email service" that would send out an email each month. For this, we could also use s3 (and demonstrate its usage) to keep a record of which customers were billed already.

My opinion is that any unique use of the shuttle features that can be shown through an example is very appreciated. What functionalities would you like to showcase? I am happy with whatever really even if we repeat some of the features usage. Also the `invoicing email service` sounds cool and useful.

> Another idea would be to make this into a "call API on a schedule" service, replacing a job function with a URL to call. This could also use s3 to keep an actual crontab which could be filled by a very simple browser frontend. The called API would perform the actual job, which may be another shuttle example (e.g. "run example X in another terminal and input its URL here to trigger it on a schedule")

I guess this one was re-phrased during the Q&A sesh as add a shuttle cron resource. As for what the functionality should do, would be great to underline it in a dedicated github issue where we can discuss about the design.

**Comment by morlinbrot** [comment]
Closing this as it is now superseded by [this](https://github.com/shuttle-hq/shuttle/pull/905) and [this](https://github.com/shuttle-hq/shuttle-examples/pull/47)

**Pull request closed without merging**
