### PR TITLE
feat: document new init command, add community examples list

### PR DESCRIPTION
**Pull request by jonaro00**
New init command + small tutorial.

RFC:
- Is the format of the list+links good? (will fill out the rest of them if approved)
- Is the sketch for a community list good? I think having the command listed is too much, it should be clear how to clone based on the tutorial.

### CODE REVIEW

**Comment by ivancernja** [comment]
Hey @jonaro00 , thanks for this. Imo it looks good!

A couple of thoughts:
1. I assume feedback needed for this PR covers just the README of the examples folder?
2. Not sure whether it's too relevant to include cloning from other platforms (eg. BB)
3. The 'Official examples' list might get too long, perhaps worth doing that one as a table as well?

Other than that, lgtm!

**Comment by jonaro00** [comment]
1. Yes, only that file is changed.
2. Those are features included for free from using cargo-generate. They might not be popular, but mentioning them is good. It can be done more briefly tho.
3. Not sure if a table or list will take more space. But I agree that it can be a table.

**Comment by jonaro00** [comment]
Full list is now written. This is what it looks like rendered on GitHub https://github.com/jonaro00/shuttle-examples/blob/feat/new-init-command/README.md

**Comment by jonaro00** [comment]
Should command and description fields change place?
Is the table too verbose? 
Are the blank rows between frameworks good?

**Comment by ivancernja** [comment]
@jonaro00 

1. Yep, would be good
2. I like it, but let's get one more opinion here @oddgrd 
3. I would ditch them. They give off a "typo" expression imo, wdyt?

Other:
1. I feel like the full-stack templates don't fit here but I'm also unsure where they would fit. Wdyt is the best way to distinguish those? Going for a separate 'full-stack' section would seem a bit too odd imo.
2. I'm a bit late to the party but is there any way we could shorten the commands for initializing examples? Something along the lines of:

`cargo shuttle init --from shuttle-hq/shuttle-examples --subfolder thruster/postgres` to
`cargo shuttle init --example thruster/postgres` or if it's a community example:
`cargo shuttle init --example community/thruster/postgres`

command feedback alias

**Comment by ivancernja** [comment]
Other than that, love the README!

**Comment by jonaro00** [comment]
1. Not sure. Since there is only one of them thus far, it is hard to classify its belonging. We can wait and see where things head if more of those pop up.
2. We discussed this when implementing the feature: https://github.com/shuttle-hq/shuttle/pull/984#discussion_r1232428630 TLDR: We decided that hardcoding the list of examples was not the way to go. @iulianbarbu thought using the long format for the examples repo was a good way to teach the user about the --from flag, while still having the hello-world examples super simple for beginners. I see your approach would just be a shorthand for cloning --from shuttle-hq/shuttle-examples. If that was added, we can update this list.

> command feedback alias

Was there anything else you were going to add?

**Comment by jonaro00** [comment]
Addressed 1. and 3. Ready to merge except if there is anything to add. (maybe remove the examples community entry)

**Review by oddgrd — APPROVED** [review]
Looks great to me, thanks! I think the extra cargo-generate docs are nice to have too.

**Pull request merged**
